# -*- coding: utf-8 -*-
"""Full-year fixed menologion for the Romanian Orthodox calendar.

Every day of the year carries a commemoration — that is what a calendar *is*.
This table supplies the base entry for all 365 (366) days; `feasts.json`
overrides it where a day needs a rank, a dezlegare or a longer name.

UNVERIFIED. Written from knowledge of the synaxarion, not transcribed from a
source. The major days are reliable; the minor ones need checking against the
Patriarchate's printed calendar before anyone leans on them. `verified` stays 0
until a human signs off, and `tool/verify_menologion.py` exists to diff this
against a trusted list once you have one.
"""

MENOLOGION: dict[str, str] = {
    # ------------------------------------------------------------- ianuarie
    "01-01": "Tăierea împrejur cea după trup a Domnului; Sf. Ier. Vasile cel Mare",
    "01-02": "Sf. Ier. Silvestru, episcopul Romei; Sf. Cuv. Serghie",
    "01-03": "Sf. Proroc Maleahi; Sf. Mc. Gordie",
    "01-04": "Soborul Sfinților 70 de Apostoli; Sf. Cuv. Teoctist",
    "01-05": "Sf. Mc. Teopempt și Teona; Sf. Cuv. Sinclitichia (Ajunul Bobotezei)",
    "01-06": "Botezul Domnului (Boboteaza)",
    "01-07": "Soborul Sf. Proroc Ioan Botezătorul",
    "01-08": "Sf. Cuv. Gheorghe Hozevitul; Sf. Cuv. Domnica",
    "01-09": "Sf. Mc. Polieuct; Sf. Ier. Petru, episcopul Sevastiei",
    "01-10": "Sf. Ier. Grigorie de Nyssa; Sf. Cuv. Antipa de la Calapodești",
    "01-11": "Sf. Cuv. Teodosie, începătorul vieții de obște",
    "01-12": "Sf. Mc. Tatiana diaconița; Sf. Mc. Mertie",
    "01-13": "Sf. Mc. Ermil și Stratonic",
    "01-14": "Sf. Cuv. Mucenici din Sinai și Rait; Sf. Nina",
    "01-15": "Sf. Cuv. Pavel Tebeul și Ioan Colibașul",
    "01-16": "Cinstirea lanțului Sf. Ap. Petru",
    "01-17": "Sf. Cuv. Antonie cel Mare",
    "01-18": "Sf. Ier. Atanasie și Chiril, arhiepiscopii Alexandriei",
    "01-19": "Sf. Cuv. Macarie Egipteanul; Sf. Ier. Marcu Eugenicul",
    "01-20": "Sf. Cuv. Eftimie cel Mare",
    "01-21": "Sf. Cuv. Maxim Mărturisitorul; Sf. Mc. Neofit",
    "01-22": "Sf. Ap. Timotei; Sf. Cuv. Mc. Anastasie Persul",
    "01-23": "Sf. Sfințit Mc. Clement; Sf. Mc. Agatanghel",
    "01-24": "Sf. Cuv. Xenia Romana; Sf. Cuv. Xenia din Petersburg",
    "01-25": "Sf. Ier. Grigorie Teologul, arhiepiscopul Constantinopolului",
    "01-26": "Sf. Cuv. Xenofont și soția sa Maria",
    "01-27": "Aducerea moaștelor Sf. Ier. Ioan Gură de Aur",
    "01-28": "Sf. Cuv. Efrem Sirul; Sf. Cuv. Isaac Sirul",
    "01-29": "Aducerea moaștelor Sf. Sfințit Mc. Ignatie Teoforul",
    "01-30": "Sfinții Trei Ierarhi: Vasile cel Mare, Grigorie Teologul și Ioan Gură de Aur",
    "01-31": "Sf. Mc. doctori fără de arginți Chir și Ioan",
    # ------------------------------------------------------------ februarie
    "02-01": "Sf. Mc. Trifon; Înainte-prăznuirea Întâmpinării Domnului",
    "02-02": "Întâmpinarea Domnului",
    "02-03": "Sf. și Dreptul Simeon, primitorul de Dumnezeu, și Sf. Proorociță Ana",
    "02-04": "Sf. Cuv. Isidor Pelusiotul; Sf. Cuv. Nicolae Mărturisitorul",
    "02-05": "Sf. Mc. Agata; Sf. Mc. Teodula",
    "02-06": "Sf. Ier. Vucol; Sf. Ier. Fotie, patriarhul Constantinopolului",
    "02-07": "Sf. Ier. Partenie; Sf. Cuv. Luca din Elada",
    "02-08": "Sf. M. Mc. Teodor Stratilat; Sf. Proroc Zaharia",
    "02-09": "Sf. Mc. Nichifor; Odovania Întâmpinării Domnului",
    "02-10": "Sf. Sfințit Mc. Haralambie",
    "02-11": "Sf. Sfințit Mc. Vlasie; Sf. Teodora împărăteasa",
    "02-12": "Sf. Ier. Meletie, arhiepiscopul Antiohiei",
    "02-13": "Sf. Cuv. Martinian; Sf. Ap. Acvila și Priscila",
    "02-14": "Sf. Cuv. Auxentie; Sf. Cuv. Chiril, apostolul slavilor",
    "02-15": "Sf. Ap. Onisim",
    "02-16": "Sf. Mc. Pamfil; Sf. Cuv. Flavian",
    "02-17": "Sf. M. Mc. Teodor Tiron",
    "02-18": "Sf. Ier. Leon, papă al Romei",
    "02-19": "Sf. Ap. Arhip, Filimon și Apfia",
    "02-20": "Sf. Ier. Leon, episcopul Cataniei",
    "02-21": "Sf. Cuv. Timotei; Sf. Ier. Eustatie al Antiohiei",
    "02-22": "Aflarea moaștelor Sfinților Mucenici din Evghenia",
    "02-23": "Sf. Sfințit Mc. Policarp, episcopul Smirnei",
    "02-24": "Întâia și a doua aflare a capului Sf. Ioan Botezătorul",
    "02-25": "Sf. Ier. Tarasie, patriarhul Constantinopolului",
    "02-26": "Sf. Ier. Porfirie, episcopul Gazei",
    "02-27": "Sf. Cuv. Procopie Decapolitul",
    "02-28": "Sf. Cuv. Vasile Mărturisitorul",
    "02-29": "Sf. Cuv. Casian Romanul",
    # ---------------------------------------------------------------- martie
    "03-01": "Sf. Cuv. Mc. Evdochia",
    "03-02": "Sf. Mc. Isihie; Sf. Mc. Teodot",
    "03-03": "Sf. Mc. Eutropie, Cleonic și Vasilisc",
    "03-04": "Sf. Cuv. Gherasim de la Iordan",
    "03-05": "Sf. Mc. Conon; Sf. Mc. Arhelau",
    "03-06": "Sf. 42 de Mucenici din Amoreea",
    "03-07": "Sf. Sfințiți Mucenici episcopi din Cherson",
    "03-08": "Sf. Ier. Teofilact, episcopul Nicomidiei",
    "03-09": "Sf. 40 de Mucenici din Sevastia",
    "03-10": "Sf. Mc. Codrat; Sf. Mc. Ciprian",
    "03-11": "Sf. Ier. Sofronie, patriarhul Ierusalimului",
    "03-12": "Sf. Cuv. Teofan Mărturisitorul; Sf. Ier. Grigorie Dialogul",
    "03-13": "Aducerea moaștelor Sf. Ier. Nichifor",
    "03-14": "Sf. Cuv. Benedict de Nursia",
    "03-15": "Sf. Mc. Agapie și cei împreună cu el",
    "03-16": "Sf. Mc. Sabin; Sf. Mc. Papa",
    "03-17": "Sf. Cuv. Alexie, omul lui Dumnezeu",
    "03-18": "Sf. Ier. Chiril, arhiepiscopul Ierusalimului",
    "03-19": "Sf. Mc. Hrisant și Daria",
    "03-20": "Sf. Cuvioși Mucenici din Mănăstirea Sf. Sava",
    "03-21": "Sf. Ier. Iacob Mărturisitorul",
    "03-22": "Sf. Sfințit Mc. Vasile, preotul din Ancira",
    "03-23": "Sf. Cuv. Mc. Nicon și cei 199 de ucenici ai săi",
    "03-24": "Sf. Cuv. Zaharia; Înainte-prăznuirea Bunei Vestiri",
    "03-25": "Buna Vestire",
    "03-26": "Soborul Sf. Arhanghel Gavriil",
    "03-27": "Sf. Mc. Matrona din Tesalonic",
    "03-28": "Sf. Cuv. Ilarion cel Nou; Sf. Cuv. Ștefan",
    "03-29": "Sf. Cuv. Marcu, episcopul Aretuselor",
    "03-30": "Sf. Cuv. Ioan Scărarul",
    "03-31": "Sf. Sfințit Mc. Ipatie, episcopul Gangrei",
    # --------------------------------------------------------------- aprilie
    "04-01": "Sf. Cuv. Maria Egipteanca",
    "04-02": "Sf. Cuv. Tit, făcătorul de minuni",
    "04-03": "Sf. Cuv. Nichita Mărturisitorul",
    "04-04": "Sf. Cuv. Gheorghe din Maleon; Sf. Cuv. Iosif Imnograful",
    "04-05": "Sf. Mc. Claudiu, Diodor și Victor",
    "04-06": "Sf. Ier. Eutihie, patriarhul Constantinopolului",
    "04-07": "Sf. Ier. Gheorghe, episcopul Mitilenei; Sf. Cuv. Nil",
    "04-08": "Sf. Ap. Irodion, Agav și Ruf",
    "04-09": "Sf. Mc. Eupsihie",
    "04-10": "Sf. Mc. Terentie și Pompei",
    "04-11": "Sf. Ier. Calinic de la Cernica; Sf. Sfințit Mc. Antipa",
    "04-12": "Sf. Cuv. Vasile Mărturisitorul, episcopul Pariei",
    "04-13": "Sf. Sfințit Mc. Artemon",
    "04-14": "Sf. Ier. Martin Mărturisitorul, papă al Romei",
    "04-15": "Sf. Ap. Aristarh, Pud și Trofim",
    "04-16": "Sf. Mc. Agapia, Irina și Hionia",
    "04-17": "Sf. Cuv. Simeon; Sf. Cuv. Acachie",
    "04-18": "Sf. Cuv. Ioan, ucenicul Sf. Grigorie Decapolitul",
    "04-19": "Sf. Cuv. Ioan din Vechea Lavră",
    "04-20": "Sf. Cuv. Teodor Trihina",
    "04-21": "Sf. Sfințit Mc. Ianuarie",
    "04-22": "Sf. Cuv. Teodor Sicheotul",
    "04-23": "Sf. M. Mc. Gheorghe, Purtătorul de biruință",
    "04-24": "Sf. Mc. Sava Stratilat; Sf. Cuv. Elisabeta",
    "04-25": "Sf. Ap. și Ev. Marcu; Sf. Cuv. Vasile de la Poiana Mărului",
    "04-26": "Sf. Sfințit Mc. Vasile, episcopul Amasiei",
    "04-27": "Sf. Sfințit Mc. Simeon, ruda Domnului",
    "04-28": "Sf. Ap. Iason și Sosipatru",
    "04-29": "Sf. 9 Mucenici din Cizic; Sf. Cuv. Memnon",
    "04-30": "Sf. Ap. Iacob, fratele Sf. Ioan Teologul",
    # ------------------------------------------------------------------- mai
    "05-01": "Sf. Proroc Ieremia; Sf. Cuv. Mc. Eftimie",
    "05-02": "Aducerea moaștelor Sf. Ier. Atanasie cel Mare",
    "05-03": "Sf. Mc. Timotei și Maura; Sf. Cuv. Irodion de la Lainici",
    "05-04": "Sf. Mc. Pelaghia",
    "05-05": "Sf. M. Mc. Irina",
    "05-06": "Sf. și Dreptul Iov; Sf. Mc. Varvar",
    "05-07": "Arătarea pe cer a Sfintei Cruci; Sf. Mc. Acachie",
    "05-08": "Sf. Ap. și Ev. Ioan Teologul; Sf. Cuv. Arsenie cel Mare",
    "05-09": "Sf. Proroc Isaia; Sf. Mc. Hristofor",
    "05-10": "Sf. Ap. Simon Zilotul",
    "05-11": "Sf. Sfințit Mc. Mochie; Sf. Ier. Chiril și Metodie",
    "05-12": "Sf. Ier. Epifanie; Sf. Ier. Gherman",
    "05-13": "Sf. Mc. Glicheria",
    "05-14": "Sf. Mc. Isidor din Hios",
    "05-15": "Sf. Cuv. Pahomie cel Mare; Sf. Ier. Iachint",
    "05-16": "Sf. Cuv. Teodor cel Sfințit",
    "05-17": "Sf. Ap. Andronic și Iunia",
    "05-18": "Sf. Mc. Petru, Dionisie și Cristina",
    "05-19": "Sf. Sfințit Mc. Patrichie",
    "05-20": "Sf. Mc. Talaleu; Sf. Cuv. Talasie",
    "05-21": "Sf. Împărați Constantin și Elena, întocmai cu apostolii",
    "05-22": "Sf. Mc. Vasilisc; Sf. Cuv. Sofia doctorița",
    "05-23": "Sf. Cuv. Mihail Mărturisitorul",
    "05-24": "Sf. Cuv. Simeon din Muntele Minunat",
    "05-25": "A treia aflare a capului Sf. Ioan Botezătorul",
    "05-26": "Sf. Ap. Carp și Alfeu",
    "05-27": "Sf. Sfințit Mc. Eladie; Sf. Mc. Iuliu Veteranul",
    "05-28": "Sf. Ier. Nichita, episcopul Calcedonului",
    "05-29": "Sf. Cuv. Mc. Teodosia",
    "05-30": "Sf. Cuv. Isaachie Mărturisitorul",
    "05-31": "Sf. Ap. Erma; Sf. Mc. Ermie",
    # ----------------------------------------------------------------- iunie
    "06-01": "Sf. Mc. Iustin Martirul și Filosoful",
    "06-02": "Sf. Ioan cel Nou de la Suceava",
    "06-03": "Sf. Mc. Luchilian și cei împreună cu el",
    "06-04": "Sf. Ier. Mitrofan, patriarhul Constantinopolului",
    "06-05": "Sf. Sfințit Mc. Doroftei, episcopul Tirului",
    "06-06": "Sf. Cuv. Visarion; Sf. Cuv. Ilarion cel Nou",
    "06-07": "Sf. Sfințit Mc. Teodot; Sf. Mc. Zenaida",
    "06-08": "Aducerea moaștelor Sf. M. Mc. Teodor Stratilat",
    "06-09": "Sf. Ier. Chiril, arhiepiscopul Alexandriei",
    "06-10": "Sf. Sfințit Mc. Timotei, episcopul Prusei",
    "06-11": "Sf. Ap. Bartolomeu și Barnaba",
    "06-12": "Sf. Cuv. Onufrie cel Mare; Sf. Cuv. Petru Athonitul",
    "06-13": "Sf. Mc. Achilina; Sf. Ier. Trifilie",
    "06-14": "Sf. Proroc Elisei; Sf. Ier. Metodie",
    "06-15": "Sf. Proroc Amos; Sf. Ier. Ieronim",
    "06-16": "Sf. Ier. Tihon, episcopul Amatundei",
    "06-17": "Sf. Mc. Manuil, Savel și Ismail",
    "06-18": "Sf. Mc. Leontie; Sf. Cuv. Erasm",
    "06-19": "Sf. Ap. Iuda, ruda Domnului",
    "06-20": "Sf. Sfințit Mc. Metodie, episcopul Patarelor",
    "06-21": "Sf. Mc. Iulian din Tars",
    "06-22": "Sf. Sfințit Mc. Eusebiu; Sf. Ier. Grigorie Dascălul",
    "06-23": "Sf. Mc. Agripina",
    "06-24": "Nașterea Sf. Proroc Ioan Botezătorul",
    "06-25": "Sf. Cuv. Mc. Fevronia",
    "06-26": "Sf. Cuv. David din Tesalonic",
    "06-27": "Sf. Cuv. Samson, primitorul de străini",
    "06-28": "Aflarea moaștelor Sf. Chir și Ioan",
    "06-29": "Sf. Ap. Petru și Pavel",
    "06-30": "Soborul Sf. 12 Apostoli; Sf. Ier. Andrei Șaguna",
    # ----------------------------------------------------------------- iulie
    "07-01": "Sf. Mc. doctori fără de arginți Cosma și Damian",
    "07-02": "Așezarea veșmântului Maicii Domnului; Sf. Voievod Ștefan cel Mare",
    "07-03": "Sf. Mc. Iachint; Sf. Ier. Anatolie",
    "07-04": "Sf. Ier. Andrei, arhiepiscopul Cretei",
    "07-05": "Sf. Cuv. Atanasie Athonitul",
    "07-06": "Sf. Cuv. Sisoe cel Mare",
    "07-07": "Sf. Cuv. Toma din Maleon; Sf. Mc. Chiriachi",
    "07-08": "Sf. M. Mc. Procopie",
    "07-09": "Sf. Sfințit Mc. Pangratie",
    "07-10": "Sf. 45 de Mucenici din Nicopolea Armeniei",
    "07-11": "Sf. M. Mc. Eufimia; Sf. Olga",
    "07-12": "Sf. Mc. Proclu și Ilarie; Sf. Cuv. Paisie Aghioritul",
    "07-13": "Soborul Sf. Arhanghel Gavriil; Sf. Cuv. Ștefan Savaitul",
    "07-14": "Sf. Ap. Achila; Sf. Cuv. Nicodim Aghioritul",
    "07-15": "Sf. Mc. Chiric și Iulita",
    "07-16": "Sf. Sfințit Mc. Atinoghen",
    "07-17": "Sf. M. Mc. Marina",
    "07-18": "Sf. Mc. Emilian; Sf. Mc. Iachint",
    "07-19": "Sf. Cuv. Macrina; Sf. Cuv. Die",
    "07-20": "Sf. Proroc Ilie Tesviteanul",
    "07-21": "Sf. Cuv. Simeon și Ioan; Sf. Proroc Iezechiel",
    "07-22": "Sf. Mironosiță și întocmai cu apostolii Maria Magdalena",
    "07-23": "Sf. Mc. Foca; Sf. Proroc Iezechiel",
    "07-24": "Sf. M. Mc. Cristina; Sf. Mc. Ermoghen",
    "07-25": "Adormirea Sf. Ana, mama Născătoarei de Dumnezeu",
    "07-26": "Sf. Sfințit Mc. Ermolae; Sf. Cuv. Mc. Parascheva",
    "07-27": "Sf. M. Mc. și Tămăduitor Pantelimon",
    "07-28": "Sf. Ap. și diaconi Prohor, Nicanor, Timon și Parmena",
    "07-29": "Sf. Mc. Calinic; Sf. Mc. Teodota",
    "07-30": "Sf. Ap. Sila, Silvan și Crescent",
    "07-31": "Sf. și Dreptul Evdochim; Înainte-prăznuirea Scoaterii Sfintei Cruci",
    # ---------------------------------------------------------------- august
    "08-01": "Scoaterea Sfintei Cruci; Sf. 7 Mucenici Macabei",
    "08-02": "Aducerea moaștelor Sf. Arhidiacon Ștefan",
    "08-03": "Sf. Cuv. Isaachie, Dalmat și Faust; Sf. Cuv. Gheorghe de la Cernica",
    "08-04": "Sf. 7 tineri din Efes",
    "08-05": "Sf. Mc. Evsignie; Sf. Cuv. Ioan Iacob de la Neamț",
    "08-06": "Schimbarea la Față a Domnului",
    "08-07": "Sf. Cuv. Mc. Dometie",
    "08-08": "Sf. Ier. Emilian Mărturisitorul",
    "08-09": "Sf. Ap. Matia",
    "08-10": "Sf. Mc. Lavrentie arhidiaconul",
    "08-11": "Sf. Mc. Evplu arhidiaconul",
    "08-12": "Sf. Mc. Fotie și Anichit",
    "08-13": "Mutarea moaștelor Sf. Cuv. Maxim Mărturisitorul",
    "08-14": "Sf. Proroc Miheia; Înainte-prăznuirea Adormirii Maicii Domnului",
    "08-15": "Adormirea Maicii Domnului",
    "08-16": "Aducerea Sfintei Mahrame; Sfinții Martiri Brâncoveni",
    "08-17": "Sf. Mc. Miron",
    "08-18": "Sf. Mc. Flor și Lavru",
    "08-19": "Sf. Mc. Andrei Stratilat",
    "08-20": "Sf. Proroc Samuel",
    "08-21": "Sf. Ap. Tadeu; Sf. Mc. Vasa",
    "08-22": "Sf. Mc. Agatonic",
    "08-23": "Odovania Adormirii Maicii Domnului; Sf. Mc. Lup",
    "08-24": "Sf. Sfințit Mc. Eutihie",
    "08-25": "Aducerea moaștelor Sf. Ap. Bartolomeu; Sf. Ap. Tit",
    "08-26": "Sf. Mc. Adrian și Natalia",
    "08-27": "Sf. Cuv. Pimen cel Mare",
    "08-28": "Sf. Cuv. Moise Etiopianul",
    "08-29": "Tăierea Capului Sf. Proroc Ioan Botezătorul",
    "08-30": "Sf. Ier. Alexandru, Ioan și Pavel cel Nou",
    "08-31": "Așezarea brâului Maicii Domnului",
    # ------------------------------------------------------------ septembrie
    "09-01": "Începutul anului bisericesc; Sf. Cuv. Simeon Stâlpnicul",
    "09-02": "Sf. Mc. Mamant; Sf. Ier. Ioan Postitorul",
    "09-03": "Sf. Sfințit Mc. Antim, episcopul Nicomidiei",
    "09-04": "Sf. Sfințit Mc. Vavila; Sf. Proroc Moise",
    "09-05": "Sf. Proroc Zaharia, tatăl Sf. Ioan Botezătorul",
    "09-06": "Pomenirea minunii Sf. Arhanghel Mihail în Colose",
    "09-07": "Înainte-prăznuirea Nașterii Maicii Domnului; Sf. Mc. Sozont",
    "09-08": "Nașterea Maicii Domnului",
    "09-09": "Sf. și Drepții Dumnezeiești Părinți Ioachim și Ana",
    "09-10": "Sf. Mc. Minodora, Mitrodora și Nimfodora",
    "09-11": "Sf. Cuv. Teodora din Alexandria",
    "09-12": "Odovania Nașterii Maicii Domnului",
    "09-13": "Sf. Ier. Iosif cel Nou de la Partoș; Înainte-prăznuirea Înălțării Sfintei Cruci",
    "09-14": "Înălțarea Sfintei Cruci",
    "09-15": "Sf. M. Mc. Nichita",
    "09-16": "Sf. M. Mc. Eufimia",
    "09-17": "Sf. Mc. Sofia și fiicele sale Pistis, Elpis și Agapis",
    "09-18": "Sf. Cuv. Eumenie",
    "09-19": "Sf. Mc. Trofim, Savatie și Dorimedont",
    "09-20": "Sf. M. Mc. Eustatie și soția sa Teopista",
    "09-21": "Odovania Înălțării Sfintei Cruci; Sf. Ap. Codrat",
    "09-22": "Sf. Sfințit Mc. Foca",
    "09-23": "Zămislirea Sf. Proroc Ioan Botezătorul",
    "09-24": "Sf. M. Mc. Tecla, întâia muceniță",
    "09-25": "Sf. Cuv. Eufrosina; Sf. Cuv. Serghie de Radonej",
    "09-26": "Adormirea Sf. Ap. și Ev. Ioan Teologul",
    "09-27": "Sf. Ier. Antim Ivireanul; Sf. Mc. Calistrat",
    "09-28": "Sf. Cuv. Hariton Mărturisitorul; Sf. Voievod Neagoe Basarab",
    "09-29": "Sf. Cuv. Chiriac Sihastrul",
    "09-30": "Sf. Sfințit Mc. Grigorie Luminătorul",
    # -------------------------------------------------------------- octombrie
    "10-01": "Acoperământul Maicii Domnului; Sf. Ap. Anania; Sf. Cuv. Iosif de la Văratec",
    "10-02": "Sf. Sfințit Mc. Ciprian; Sf. Mc. Iustina",
    "10-03": "Sf. Sfințit Mc. Dionisie Areopagitul",
    "10-04": "Sf. Sfințit Mc. Ierotei, episcopul Atenei",
    "10-05": "Sf. Mc. Haritina",
    "10-06": "Sf. Ap. Toma",
    "10-07": "Sf. Mc. Serghie și Vach",
    "10-08": "Sf. Cuv. Pelaghia",
    "10-09": "Sf. Ap. Iacob al lui Alfeu; Sf. Cuv. Andronic",
    "10-10": "Sf. Mc. Evlampie și Evlampia",
    "10-11": "Sf. Ap. Filip, unul din cei șapte diaconi",
    "10-12": "Sf. Mc. Prov, Tarah și Andronic",
    "10-13": "Sf. Mc. Carp, Papil și Agatonica",
    "10-14": "Sf. Cuv. Parascheva de la Iași",
    "10-15": "Sf. Cuv. Mc. Lucian",
    "10-16": "Sf. Mc. Longin sutașul",
    "10-17": "Sf. Proroc Osea; Sf. Cuv. Mc. Andrei Criteanul",
    "10-18": "Sf. Ap. și Ev. Luca",
    "10-19": "Sf. Proroc Ioil; Sf. Mc. Uar",
    "10-20": "Sf. M. Mc. Artemie; Sf. Cuv. Gherasim",
    "10-21": "Sf. Cuv. Ilarion cel Mare",
    "10-22": "Sf. Ier. Averchie; Sf. 7 tineri din Efes",
    "10-23": "Sf. Ap. Iacob, ruda Domnului",
    "10-24": "Sf. Mc. Areta; Sf. Cuv. Elesbaan",
    "10-25": "Sf. Mc. Marcian și Martirie",
    "10-26": "Sf. M. Mc. Dimitrie, Izvorâtorul de Mir",
    "10-27": "Sf. Cuv. Dimitrie cel Nou, ocrotitorul Bucureștilor",
    "10-28": "Sf. Mc. Terentie și Neonila; Sf. Ier. Iachint de Vicina",
    "10-29": "Sf. Cuv. Mc. Anastasia Romana; Sf. Cuv. Avramie",
    "10-30": "Sf. Mc. Zenobie și sora sa Zenobia",
    "10-31": "Sf. Ap. Stahie, Amplie și Urban",
    # --------------------------------------------------------------- noiembrie
    "11-01": "Sf. Mc. doctori fără de arginți Cosma și Damian din Asia",
    "11-02": "Sf. Mc. Achindin, Pigasie și cei împreună cu ei",
    "11-03": "Sf. Mc. Achepsima; Sf. Cuv. Ioanichie",
    "11-04": "Sf. Cuv. Ioanichie cel Mare",
    "11-05": "Sf. Mc. Galaction și Epistimia",
    "11-06": "Sf. Ier. Pavel Mărturisitorul",
    "11-07": "Sf. 33 de Mucenici din Melitina",
    "11-08": "Soborul Sf. Arhangheli Mihail și Gavriil",
    "11-09": "Sf. Mc. Onisifor; Sf. Cuv. Matrona",
    "11-10": "Sf. Ap. Olimp, Rodion și Erast",
    "11-11": "Sf. M. Mc. Mina; Sf. Mc. Victor și Vichentie",
    "11-12": "Sf. Ier. Ioan cel Milostiv; Sf. Cuv. Nil",
    "11-13": "Sf. Ier. Ioan Gură de Aur",
    "11-14": "Sf. Ap. Filip (Lăsatul secului pentru Postul Nașterii Domnului)",
    "11-15": "Sf. Mc. Gurie, Samona și Aviv; Sf. Cuv. Paisie de la Neamț",
    "11-16": "Sf. Ap. și Ev. Matei",
    "11-17": "Sf. Ier. Grigorie, episcopul Neocezareei",
    "11-18": "Sf. Mc. Platon și Roman",
    "11-19": "Sf. Proroc Avdie; Sf. Mc. Varlaam",
    "11-20": "Sf. Cuv. Grigorie Decapolitul; Înainte-prăznuirea Intrării în Biserică",
    "11-21": "Intrarea în Biserică a Maicii Domnului",
    "11-22": "Sf. Ap. Filimon, Arhip și Apfia",
    "11-23": "Sf. Ier. Amfilohie și Grigorie",
    "11-24": "Sf. Sfințit Mc. Clement, episcopul Romei",
    "11-25": "Sf. M. Mc. Ecaterina; Sf. M. Mc. Mercurie",
    "11-26": "Sf. Cuv. Alipie Stâlpnicul; Sf. Cuv. Nicon",
    "11-27": "Sf. M. Mc. Iacob Persul",
    "11-28": "Sf. Cuv. Mc. Ștefan cel Nou",
    "11-29": "Sf. Mc. Paramon și Filumen",
    "11-30": "Sf. Ap. Andrei, cel Întâi chemat, Ocrotitorul României",
    # --------------------------------------------------------------- decembrie
    "12-01": "Sf. Proroc Naum; Sf. Cuv. Filaret Milostivul",
    "12-02": "Sf. Proroc Avacum; Sf. Cuv. Ioan Pustnicul",
    "12-03": "Sf. Proroc Sofonie; Sf. Cuv. Teodul",
    "12-04": "Sf. M. Mc. Varvara; Sf. Cuv. Ioan Damaschin",
    "12-05": "Sf. Cuv. Sava cel Sfințit",
    "12-06": "Sf. Ier. Nicolae, arhiepiscopul Mirelor Lichiei",
    "12-07": "Sf. Ier. Ambrozie, episcopul Mediolanului",
    "12-08": "Sf. Cuv. Patapie",
    "12-09": "Zămislirea Sf. Fecioare Maria de către Sf. Ana",
    "12-10": "Sf. Mc. Mina, Ermoghen și Eugraf",
    "12-11": "Sf. Cuv. Daniil Stâlpnicul",
    "12-12": "Sf. Ier. Spiridon, episcopul Trimitundei",
    "12-13": "Sf. Mc. Eustratie, Auxentie, Evghenie, Mardarie și Orest",
    "12-14": "Sf. Mc. Tirs, Levchie și Calinic",
    "12-15": "Sf. Sfințit Mc. Elefterie",
    "12-16": "Sf. Proroc Agheu",
    "12-17": "Sf. Proroc Daniel și cei trei tineri",
    "12-18": "Sf. Mc. Sebastian și cei împreună cu el",
    "12-19": "Sf. Mc. Bonifatie",
    "12-20": "Sf. Sfințit Mc. Ignatie Teoforul",
    "12-21": "Sf. Mc. Iuliana; Odovania Intrării în Biserică",
    "12-22": "Sf. M. Mc. Anastasia",
    "12-23": "Sf. 10 Mucenici din Creta",
    "12-24": "Sf. Cuv. Mc. Eugenia (Ajunul Nașterii Domnului)",
    "12-25": "Nașterea Domnului (Crăciunul)",
    "12-26": "Soborul Maicii Domnului",
    "12-27": "Sf. Arhidiacon Ștefan, întâiul mucenic",
    "12-28": "Sf. 20.000 de Mucenici arși în Nicomidia",
    "12-29": "Sf. 14.000 de prunci uciși de Irod",
    "12-30": "Sf. Mc. Anisia; Sf. Cuv. Teodora",
    "12-31": "Sf. Cuv. Melania Romana",
}
